name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: ["14", "16", "18"]
        vite: ["2", "3"]
    name: Node.js ${{ matrix.node }} + Vite ${{ matrix.vite }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Install specified version of Vite
        run: yarn add vite@^${{ matrix.vite }}
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Check style
        if: ${{ matrix.os != 'windows-latest' }}
        run: yarn format --check
